- index.html
Change Get Started button to point to the updated Getting Started.
Change the Download button to point to the Building/Install docs.
> link to more appropriate parts of the docs

- index.html
Currently `https://www.envoyproxy.io/docs/envoy/latest/install/getting_started` is returning a 404.
Signed-off-by: Anubhav Mishra <anubhavmishra@me.com>
> Fix broken getting started link

- docs.md
We already released v1.6.0. Probably, follow up PR of https://github.com/envoyproxy/envoyproxy.github.io/pull/29.
@richarddli ?
Signed-off-by: Taiki Ono <taiki-ono@cookpad.com>
> Add a link to v1.6.0 docs in the docs page

- _sass/home.scss
- index.html
> Change design of Envoy version button

- README.md
- docker-compose.yml
Installing Ruby on OSX wasn't a happy experience so I went with a Docker Container. Providing the command for the next time :)
> Update README to mention how to run Envoy Proxy website using Docker

- _data/nav.yml
- _layouts/try.html
- css/main.scss
- try/api-based-dynamic-routing-configuration.md
- try/blue-green-deployments.md
- try/detecting-service-health-with-healthchecks.md
- try/file-based-dynamic-routing-configuration.md
- try/getting-started.md
- try/implementing-metrics-tracing.md
- try/index.md
- try/migrating-from-haproxy-to-envoy.md
- try/migrating-from-nginx-to-envoy.md
- try/securing-traffic-with-https.md
Embed the Katacoda interactive scenarios as https://www.envoyproxy.io/try as /learn is the Turbine Labs series. I think /try added a nice addition and capture users interest. 
The index page displays all the content available:
This takes the user to the page where they can complete the scenario.
> Embed Katacoda interactive scenarios under /try

- learn/automatic-retries.md
- learn/health-check.md
- learn/routing-basics.md
1. "aggresive" to "aggressive" in line 115.
2. "Healthly" to "Healthy" in line 3.
3. "definion" to "definition" in line 24.
> Fix some typos in docs

- learn/automatic-retries.md
The [old URL](https://www.envoyproxy.io/docs/envoy/latest/api-v1/route_config/route.html#config-http-conn-man-route-table-route-retry) is currently returning a 404 - it looks like the last version of the api docs for which the link is active is v1.8.0 so modifying it to point to that.
> Learn Envoy: Fixing an outdated URL

- README.md
The blank line is causing the last line of the table to be rendered
outside of the table, when it should be included as part of it.
> Fix table layout by removing blank line [skip ci]

- robots.txt
Addresses issue [#8838](https://github.com/envoyproxy/envoy/issues/8838) in the main Envoy repo.
This PR automatically generates a `robots.txt` file that disallows indexing of all documentation versions besides `latest`. This was initially proposed in the [main Envoy repo](https://github.com/envoyproxy/envoy/pull/9766) but it's much easier to automate here in the website repo given that the list of versions is available in `_config.yml`.
You can see the generated file here:
https://deploy-preview-139--beggar-construction-36308.netlify.com/robots.txt
> Add robots.txt file to control documentation indexing

- learn/index.md
Super basic change. A few URLs seem to have lost their targets after some doc refactorings. Also repointed the SSL link to the latest documentation instead of v1.6.0 (released in 2018).
> Fix up a few URLs

- index.html
The link used to take to the old [intro/version_history](https://www.envoyproxy.io/docs/envoy/v1.15.0/intro/version_history) page, we can just link to the newest one or maybe to the [version history listing](https://www.envoyproxy.io/docs/envoy/v1.15.0/version_history/version_history#version-history) page.
> Fix "Read the changelog" link

- _includes/header.html
This PR adds a banner for EnvoyCon 2020 registration to the site header. It implements a CSS class introduced in #56, and is essentially a retread of that PR. (Thanks, @dansipple. 👋 )
/cc @celestehorgan @caniszczyk
> Add a banner for EnvoyCon 2020

- _includes/header.html
This PR removes the site banner for EnvoyCon 2020, which concluded on October 15.
/ref #170, #56 
/cc @kkenlaw
> Remove EnvoyCon 2020 banner

- build-website.sh
Fix https://github.com/envoyproxy/envoy/issues/18355
> docs: Use full blob sha for referencing docker images

- netlify.toml
Adding Netlify redirect so that:
* https://envoyproxy.io/slack --> https://join.slack.com/t/envoyproxy/shared_invite/zt-jfib52g3-e4Zqbaw2biDWwEsa8EF60Q
As per helpdesk request [CNCFSD-1082](https://cncfservicedesk.atlassian.net/browse/CNCFSD-1082)
> adding redirect for Slack invite link.

- docs/latest_version.sh
fixes a current bug where docs are always one commit behind
> repo: Fix commit hash used for docs publishing

- build-website.sh
- Have `bazel` propagate the value of `JEKYLL_ENV` so that Jekyll knows which environment it is building in
- Closes #274
/cc @phlax
> Bazel: propagate JEKYLL_ENV

- index.html
Copied the URL that exists at the bottom of the page
Ref: https://github.com/envoyproxy/envoy-website/issues/296
> [BUGFIX] Fix download URL to /start/install

- build-website.sh
- docker-compose.yml
- site/BUILD
with this change, you can build the site with no docs:
```console
export BAZEL_BUILD_OPTIONS="--//site:no_docs_archive=True --//site:no_docs_latest=True"
docker compose run build
```
> site/build: Allow building without docs

- README.md
> repo: Docker and readme cleanups
