_data/home.yml
=> fix issue #6

index.html
=> fix version history link

index.html
=> update for 1.5

_data/nav.yml, docs.md
=> add docs landing page (#15)

_data/nav.yml
=> update for medium blog

index.html
=> update for 1.6

_data/home.yml
Signed-off-by: Dan Sipple <sipple.dan@gmail.com>
=> Correct vmware logo typo

_data/home.yml
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Fix home yml

index.html
=> remove kubecon eu banner

docs.md, index.html
=> update for 1.7 release

_includes/header.html, _sass/header.scss
Signed-off-by: Dan Sipple <sipple.dan@gmail.com>
=> Add EnvoyCon banner to website

_data/home.yml
In addition to being fewer words (always good 😀), we more publicly offer support now on [turbinelabs.io/pricing](https://www.turbinelabs.io/pricing), so that's worth mentioning.
=> Update Turbine Labs company description

_config.yml, _includes/header.html
=> update for 1.8

Makefile, README.md, _config.yml, _data/nav.yml, _layouts/learn.html, _sass/learn.scss, css/main.scss, learn/automatic-retries.md, learn/backpressure.md, learn/circuit-breaking.md, learn/front-proxy.md, learn/getting-help.md, learn/glossary.md, learn/health-check.md, learn/incremental-deploys.md, learn/index.md, learn/on-your-laptop.md, learn/routing-basics.md, learn/routing-configuration.md, learn/service-discovery.md, learn/service-mesh.md, learn/ssl.md
You can see a preview of the new "Learn" section here:
https://deploy-preview-74--teacher-glances-63085.netlify.com/learn/
=> Weave Learn Envoy content into envoyproxy.io

_data/home.yml, community.html
PR #78 erroneously put AWS App Mesh in the OSS section of the community page.
cc @caniszczyk
=> Move App Mesh into commercial section

_data/home.yml
In the last update (#100) I missed a few pieces of text to update. 
Signed-off-by: Steve Sloka <slokas@vmware.com>
=> Update description for Gimbal

_config.yml
=> update for 1.9.1

_config.yml
=> Update for 1.10.0

_data/home.yml
Should have only been under partners.
=> Remove Instana from using companies

_config.yml
=> update for 1.11

_config.yml
Signed-off-by: Stephan Zuercher <zuercher@gmail.com>
=> docs: add link for 1.11.0 docs

_config.yml
=> update for 1.11.1

_config.yml, _includes/analytics.html, _includes/head.html
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add Google Analytics

_config.yml
=> update for 1.11.2

learn/service-mesh.md
=> Fix typo and wording in service-mesh.md

_config.yml
=> update for 1.12.0

learn/on-your-laptop.md
Signed-off-by: Hendy Irawan <hendy@hendyirawan.com>
=> Windows troubleshooting tip for on-your-laptop.md

_data/home.yml, learn/front-proxy.md
Signed-off-by: James Peach <jpeach@apache.org>
=> Update Contour and Gimbal project links.

_config.yml
Signed-off-by: Michael P <michael@sooper.org>
=> Update for 1.12.2

_data/home.yml
Signed-off-by: James Peach <jpeach@apache.org>
=> Update links to the Gimbal project.

_config.yml
=> update for v1.13.0

netlify.toml, robots.txt
=> Do not index non-latest docs

README.md
An initial set of logo guidelines.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add envoy logo guidelines

learn/front-proxy.md
=> Remove unnecessary "and"

_config.yml
Signed-off-by: Michael Payne <michael@sooper.org>
=> Update for 1.13.1, 1.12.3.

_config.yml
=> release: update for 1.14.1

try/debugging-envoy-proxy.md, try/load-balancing.md
This should fix https://github.com/envoyproxy/envoyproxy.github.io/issues/141
=> Add missing try links

_config.yml
Reverts envoyproxy/envoyproxy.github.io#158 (I was too eager to merge)
Signed-off-by: Harvey Tuch <htuch@google.com>
=> Revert " docs: updating for 1.15.0"

netlify.toml
=> add csp header

_data/home.yml, img/logos/enroute.svg
Thank you @mattklein123 Here is the PR.
=> Add Enroute (Issue #165)

_config.yml
Added 1.16.1, 1.16.2, 1.15.3, 1.14.6 and 1.13.7 releases.
=> docs: added 1.16.1, 1.16.2, 1.15.3, 1.14.6 and 1.13.7 releases.

_config.yml, index.html
Signed-off-by: Michael Payne <michael@sooper.org>
=> Update website for 1.17.1

_data/home.yml
=> remove rotor

build-website.sh
=> docs: Remove tmp hash

build-website.sh
=> docs: Remove error catch from build

requirements.in, requirements.txt
=> deps: Bump sphinx-runner & pygments

requirements.in, requirements.txt
=> docs: Update pytooling deps

build-website.sh
=> repo: Fix VERSION file path

_config.yml
=> release: 1.22.0

BUILD
=> repo: Add robots.txt to bazel site build

_config.yml, docs/fetch_rst.py, site/BUILD, site/jekyll_plugins/symlink_watcher.rb, site/live.py
=> bazel: Add live site runner

docker-compose.yml, docker/Dockerfile, docker/entrypoint.sh, docs/latest_version.sh, site/live.py
=> repo: Add/update docker/compose recipe

BUILD, WORKSPACE, archive.bzl, deps.bzl, packages.bzl, site/jekyll_plugins/symlink_watcher.rb, toolchains.bzl, versions.bzl
=> repo: Website/build cleanups

_config.yml, docker-compose.yml, docker/Dockerfile, docs/BUILD, site/BUILD, site/live_docs.py
=> bazel: Add docs to live site

archive.bzl, packages.bzl, toolchains.bzl, versions.bzl
=> bazel: Cleanups

README.md, docker-compose.yml
=> repo: Rename `envoyproxy.github.io` -> `envoy-website`

_config.yml
=> site: Fix canonical name for jekyll

BUILD, CNAME
=> site: Remove `CNAME` file

package.json, yarn.lock
=> yarn: Remove ununsed netlify plugin

README.md, docker-compose.yml
=> repo: Update dev/build/deploy README

_data/versions.yml
=> docs: Add missing release version

netlify.toml
=> update slack link

docs/requirements.in, docs/requirements.txt
=> docs: Update deps (`envoy.docs.sphinx_runner`)

docs/requirements.in, docs/requirements.txt
=> deps: Bump `envoy.docs.sphinx_runner`

_config.yml
=> version: Bump latest -> 1.22.2

.github/dependabot.yml
=> repo: Add dependabot

docs/requirements.in, docs/requirements.txt
=> deps: Bump `envoy.docs.sphinx_runner` -> 0.1.8

_config.yml
@phlax not sure if this is still needed or is it being done automatically.
Just followed the [Release cutting notes](https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#cutting-a-major-release), but feel free to discard if there are automatic tools that take care of this.
Signed-off-by: Adi Suissa-Peleg <adip@google.com>
=> envoy: new Envoy version 1.23.0

docs/requirements.in, docs/requirements.txt
=> deps: Bump `envoy.docs.sphinx_runner` -> 0.1.10

.gitpod.yml
=> Add GitPod init

docs/envoy/v1.23.3/version_history/v1.23/v1.23.3.html
changelog was missing when branch was published
=> changelog: Fix for `1.23.3`

_config.yml
Signed-off-by: Kevin Baichoo <kbaichoo@google.com>
=> Update website for 1.25.0

BUILD, google95e577d28834e13d.html
=> site: Add google search console auth

_data/home.yml
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> Kuma now has a new location

_config.yml
=> site: Bump latest version -> 1.25.1

_config.yml
Per the discussion on Slack: https://envoyproxy.slack.com/archives/C78M4KW76/p1678716155836349
=> site: Bump latest version -> 1.25.2

_config.yml
site: Bump latest version to 1.27.0
=> site: Bump latest -> 1.27.0

versions.bzl
=> deps: Bump versions to fix Envoy compatibility

.github/dependabot.yml, .github/workflows/archive-sync.yaml, .github/workflows/envoy-sync.yaml
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> Setup dependabot for github-actions and pin actions versions

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/scorecard.yml, docker/Dockerfile
This also fixes dependabot config as npm is used while pip is not
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> setup ossf scorecard and codql workflows 

docker-compose.yml
=> docker/compose: Remove unused version
